before_script:
  - make clean
  - make info

stages:
  - unit-test
  - build
  - deploy

run-unit-tests:
  stage: unit-test
  script:
    - make lint
    - make unit-test

build-image:
  stage: build
  script:
    - make build-in-docker
    - make build-image

deploy-tutum:
 stage: deploy
 script:
   - make deploy-tutum
