clean: 
  script: make clean
  
test:
  script: make test
  
pack:
  script: make pack

staging:
  script: make deploy-tutum
  only:
    - dev

deploy:
  script: make deploy-tutum
  only:
    - master
